version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - website:/var/www/html
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    restart: always

volumes:
  website:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/dsy/data/website'
  db:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/dsy/data/db'

networks:
  Inception:
    driver: bridge
